//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.3
//     from Assets/Game.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Game: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Game()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Game"",
    ""maps"": [
        {
            ""name"": ""MyGame"",
            ""id"": ""cd260587-f41e-45a7-995c-295e936cae8a"",
            ""actions"": [
                {
                    ""name"": ""Down"",
                    ""type"": ""Value"",
                    ""id"": ""f2f7486d-015b-410f-9f01-76a1c755ab02"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Touch"",
                    ""type"": ""PassThrough"",
                    ""id"": ""ef85a012-1e1c-4457-ac6a-2fbf557af722"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""IsDown"",
                    ""type"": ""Value"",
                    ""id"": ""b9a478c9-3048-4258-9f24-55001f533847"",
                    ""expectedControlType"": ""Touch"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""9db79726-25e1-40a7-8c04-49526724404d"",
                    ""path"": ""<Touchscreen>/touch0/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Touch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dd4b3204-b93e-46aa-b5f8-1d1674428966"",
                    ""path"": ""<Touchscreen>/touch1/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Touch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""426af435-6790-499f-99f0-65e8866b058e"",
                    ""path"": ""<Touchscreen>/touch2/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Touch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""40857b61-c326-4ca6-953a-579ce3df51fc"",
                    ""path"": ""<Touchscreen>/touch3/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Touch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c138f4d7-7800-4a86-9a31-71b323fed969"",
                    ""path"": ""<Touchscreen>/touch4/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Touch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b119e140-184b-4dc2-9f49-3ce16221ac84"",
                    ""path"": ""<Touchscreen>/touch5/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Touch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6d3beb0e-492d-4ed4-8ec9-7d0b378e1bdd"",
                    ""path"": ""<Touchscreen>/touch6/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Touch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b9788bf8-910f-46b8-95cd-5dbd01f30f9e"",
                    ""path"": ""<Touchscreen>/touch7/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Touch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c824a13e-7184-42bf-9216-cf7c967a6c4a"",
                    ""path"": ""<Touchscreen>/touch8/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Touch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""99379347-9ab7-4656-84c9-2c9fa716472e"",
                    ""path"": ""<Touchscreen>/touch9/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Touch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ed8d7bca-81ab-4d67-8bb2-ef94da5dd55d"",
                    ""path"": ""<Mouse>/press"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9565e89c-e9b3-4414-8918-3cf112d92b19"",
                    ""path"": ""<Touchscreen>/primaryTouch"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""IsDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""906c04ab-4642-4e45-943b-3bbb9bb35be8"",
                    ""path"": ""<Pointer>/primaryTouch"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""IsDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""New control scheme"",
            ""bindingGroup"": ""New control scheme"",
            ""devices"": [
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // MyGame
        m_MyGame = asset.FindActionMap("MyGame", throwIfNotFound: true);
        m_MyGame_Down = m_MyGame.FindAction("Down", throwIfNotFound: true);
        m_MyGame_Touch = m_MyGame.FindAction("Touch", throwIfNotFound: true);
        m_MyGame_IsDown = m_MyGame.FindAction("IsDown", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // MyGame
    private readonly InputActionMap m_MyGame;
    private List<IMyGameActions> m_MyGameActionsCallbackInterfaces = new List<IMyGameActions>();
    private readonly InputAction m_MyGame_Down;
    private readonly InputAction m_MyGame_Touch;
    private readonly InputAction m_MyGame_IsDown;
    public struct MyGameActions
    {
        private @Game m_Wrapper;
        public MyGameActions(@Game wrapper) { m_Wrapper = wrapper; }
        public InputAction @Down => m_Wrapper.m_MyGame_Down;
        public InputAction @Touch => m_Wrapper.m_MyGame_Touch;
        public InputAction @IsDown => m_Wrapper.m_MyGame_IsDown;
        public InputActionMap Get() { return m_Wrapper.m_MyGame; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MyGameActions set) { return set.Get(); }
        public void AddCallbacks(IMyGameActions instance)
        {
            if (instance == null || m_Wrapper.m_MyGameActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_MyGameActionsCallbackInterfaces.Add(instance);
            @Down.started += instance.OnDown;
            @Down.performed += instance.OnDown;
            @Down.canceled += instance.OnDown;
            @Touch.started += instance.OnTouch;
            @Touch.performed += instance.OnTouch;
            @Touch.canceled += instance.OnTouch;
            @IsDown.started += instance.OnIsDown;
            @IsDown.performed += instance.OnIsDown;
            @IsDown.canceled += instance.OnIsDown;
        }

        private void UnregisterCallbacks(IMyGameActions instance)
        {
            @Down.started -= instance.OnDown;
            @Down.performed -= instance.OnDown;
            @Down.canceled -= instance.OnDown;
            @Touch.started -= instance.OnTouch;
            @Touch.performed -= instance.OnTouch;
            @Touch.canceled -= instance.OnTouch;
            @IsDown.started -= instance.OnIsDown;
            @IsDown.performed -= instance.OnIsDown;
            @IsDown.canceled -= instance.OnIsDown;
        }

        public void RemoveCallbacks(IMyGameActions instance)
        {
            if (m_Wrapper.m_MyGameActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IMyGameActions instance)
        {
            foreach (var item in m_Wrapper.m_MyGameActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_MyGameActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public MyGameActions @MyGame => new MyGameActions(this);
    private int m_NewcontrolschemeSchemeIndex = -1;
    public InputControlScheme NewcontrolschemeScheme
    {
        get
        {
            if (m_NewcontrolschemeSchemeIndex == -1) m_NewcontrolschemeSchemeIndex = asset.FindControlSchemeIndex("New control scheme");
            return asset.controlSchemes[m_NewcontrolschemeSchemeIndex];
        }
    }
    public interface IMyGameActions
    {
        void OnDown(InputAction.CallbackContext context);
        void OnTouch(InputAction.CallbackContext context);
        void OnIsDown(InputAction.CallbackContext context);
    }
}
