using UnityEngine;
using System.Collections;
using System.Collections.Generic;

public class Template3D : MonoBehaviour
{
    #region Properties
    [SerializeField]
    private string _identifier = "";
    /// <summary>
    /// The unique identifier.
    /// </summary>
	public string identifier {
		get {
			if(string.IsNullOrEmpty(_identifier)) {
				System.Guid guid = System.Guid.NewGuid();
				_identifier = guid.ToString();
			}

			return _identifier;
		}
		set {
			if(value == null) value = "";
			_identifier = value;
		}
	}

    [SerializeField]
	private int _userId = 0;
    /// <summary>
    /// The ID of the user who related by the template.
    /// </summary>
	public int userId {
		get {
			return _userId;
		}
		set {
			_userId = value;
		}
	}

    [SerializeField]
    private int _userSeq = 0;
    /// <summary>
    /// The sequence of the user who related by the template.
    /// </summary>
	public int userSeq {
		get {
			return _userSeq;
		}
		set {
			_userSeq = value;
		}
	}

    [SerializeField]
    private string _character = "";
    /// <summary>
    /// The character's name of the template.
    /// </summary>
	public string character {
		get {
			return _character;
		}
		set {
			if(value == null) value = "";
			_character = value;
		}
	}

    [SerializeField, HideInInspector]
    private byte _identifierForTCCamera = 0;
    /// <summary>
    /// The unique identifier generated by TC Camera. Don't set this value directly.
    /// </summary>
    /// <value>The identifier.</value>
	public byte identifierForTCCamera {
		get {
			return _identifierForTCCamera;
		}
		set {
			_identifierForTCCamera = value;
		}
    }

    private static TCCamera _tcCam;
    /// <summary>
    /// The reference of the TC Camera.
    /// </summary>
    private static TCCamera tcCam
    {
        get
        {
            if (_tcCam == null)
                _tcCam = TCCamera.sharedInstance;
            return _tcCam;
        }
    }

    [SerializeField, HideInInspector]
    private bool _wantsPaint = false;
	public bool wantsPaint {
		get {
			return _wantsPaint;
		}
		set {
			_wantsPaint = value;

            if (tcCam != null)
            {
                if (_wantsPaint)
                    _tcCam.RegisterTemplate(this);
                else
                    _tcCam.UnregisterTemplate(this);
            }
		}
	}

	private bool _painting = false;

	public bool painting {
		get {
			return _painting;
		}
	}

	private Transform _cachedTransform = null;
    /// <summary>
    /// Cached transform.
    /// </summary>
	public Transform cachedTransform {
		get {
			if(_cachedTransform == null)
				_cachedTransform = transform;
			return _cachedTransform;
		}
    }

    [SerializeField, HideInInspector]
    private Texture _brushTexture;
    /// <summary>
    /// The brush texture.
    /// </summary>
    public Texture brushTexture
    {
        get
        {
            if (_brushTexture == null)
            {
                _SetupBrushTexture();
            }
            return _brushTexture;
        }
    }

    private static bool _prefersComputeShaders = true;
    /// <summary>
    /// You can turn on or off the GPGPU mode. Only NVIDIA or AMD devices will support.
    /// </summary>
    public static bool prefersComputeShaders
    {
        get
        {
            if (SystemInfo.supportsComputeShaders)
            {
                return _prefersComputeShaders;
            }
            else
            {
                Debug.Log("This device doesn't support GPGPU acceleration. (Needs any NVIDIA or AMD GPU device)");
            }

            return false;
        }
        set
        {
            _prefersComputeShaders = value;

            if (supportsComputeShaders)
            {
                Debug.Log("Template3D.prefersComputeShaders : GPGPU mode is enabled.");
            }
        }
    }

    /// <summary>
    /// This property actually queries that this device supports GPGPU acceleration.
    /// </summary>
    public static bool supportsComputeShaders
    {
        get
        {
            return prefersComputeShaders && SystemInfo.supportsComputeShaders;
        }
    }

	private static ComputeShader _computeShader;
    /// <summary>
    /// The compute shader used in Template3D. Dynamically loaded in Resources.
    /// </summary>
	public static ComputeShader computeShader {
		get {
			if(_computeShader == null) {
				_computeShader = (ComputeShader)Resources.Load("ComputeShaders/TemplateDrawing");
			}
			return _computeShader;
		}
	}
    #endregion

    #region Private variables
    // Brush texture information
	private int _brushTextureWidth = 512;
    private int _brushTextureHeight = 512;
    
    // Poly Index texture
	public Texture2D polyIndexTexture;
	private byte[] _polyIndexMap = null;

    // The previous painted positions of touches
	private Dictionary<int, Vector3> _prevPaintPosDict = new Dictionary<int, Vector3>();

	// The cached UV list
	private List<Vector2> _uvs = new List<Vector2>(32);

    // The main texture
    [SerializeField]
    private Texture _mainTexture = null;

    // Materials
    private Material[] materials;

	// Software Painting
	private Color[] _brushTextureBackupColors = null;
	private Color[] _innerBrushPaintColors = null;
	private Color[] _blendedColors = null;

	// GPGPU Painting
	private static int _computeLoadKernel = -1;
	private static int _computeCleanKernel = -1;
	private static int _computePaintKernel = -1;
	private ComputeBuffer _computeUVsBuffer;
	private Vector2[] _computeUVsBufferArray;
    #endregion

    #region Constants
    // The shader name
    private const string shaderName = "Custom/Brushed Bumped Specular";

    // The mininum UV offset
    public const float kPaintUVMinOffset = 0.000000238418f;
    #endregion
    
	public void Awake()
    {
        _SetupBrushTexture(true, false);
        _SetupPolyIndexTexture();
        _SetupMaterials();

		_computeUVsBufferArray = new Vector2[32];
		_computeUVsBuffer = new ComputeBuffer(32, sizeof(float)*2, ComputeBufferType.Raw);
	}

    private void _SetupBrushTexture(bool forceCreateNewTexture = false, bool destroyPreviousBrushTexture = true)
    {
        bool createsNewTexture = false;

        // Setup brush texture
        if (_brushTexture != null && !forceCreateNewTexture)
        {
            if ((brushTexture is Texture2D && supportsComputeShaders) || (brushTexture is RenderTexture && !supportsComputeShaders))
            {
                // Check if brush texture has valid type
                createsNewTexture = true;
            }
            else if (_brushTexture.width != _brushTextureWidth || _brushTexture.height != _brushTextureHeight)
            {
                // Resize the brush texture if actual texture width or height is different
                if (supportsComputeShaders)
                {
                    // RenderTexture can't resize.
                    createsNewTexture = true;
                }
                else
                {
                    // Texture2D doesn't need to recreate. Just resize the current.
                    Texture2D tex = (Texture2D)_brushTexture;
                    tex.Reinitialize(_brushTextureWidth, _brushTextureHeight);
                    tex.Apply();
                    _brushTextureBackupColors = tex.GetPixels();
                }
            }
            else
            {
                // Valid texture
                createsNewTexture = false;
            }
        }
        else
        {
            // no texture yet
            createsNewTexture = true;
        }

        if (createsNewTexture)
        {
            Texture newBrushTexture = null;

            // Make new texture if needed
            if (supportsComputeShaders)
            {
                RenderTexture tex = new RenderTexture(_brushTextureWidth, _brushTextureHeight, 0, RenderTextureFormat.ARGB32, RenderTextureReadWrite.sRGB);
                tex.name = "brush_tex_gpgpu";
                tex.enableRandomWrite = true;
                tex.Create();
                newBrushTexture = tex;
            }
            else
            {
                newBrushTexture = new Texture2D(_brushTextureWidth, _brushTextureHeight);
                newBrushTexture.name = "brush_tex";
                _brushTextureBackupColors = ((Texture2D)newBrushTexture).GetPixels();
            }

            if (_brushTexture != null)
            {
                // Copy from previous brush texture
                if (newBrushTexture is RenderTexture)
                    Graphics.Blit(_brushTexture, (RenderTexture)newBrushTexture);
                else if (_brushTexture is RenderTexture)
                {
                    RenderTexture prev = RenderTexture.active;
                    RenderTexture.active = _brushTexture as RenderTexture;
                    ((Texture2D)newBrushTexture).ReadPixels(new Rect(0, 0, _brushTextureWidth, _brushTextureHeight), 0, 0);
                    RenderTexture.active = prev;
                    ((Texture2D)newBrushTexture).Apply();

                    _brushTextureBackupColors = ((Texture2D)newBrushTexture).GetPixels();
                }
                else
                    LoadBrushTexture(((Texture2D)_brushTexture).EncodeToPNG());

                if (destroyPreviousBrushTexture)
                {
                    // Release the previous brush texture and assign new one.
                    if (_brushTexture is RenderTexture)
                        ((RenderTexture)_brushTexture).Release();
                    Destroy(_brushTexture);
                }
                _brushTexture = newBrushTexture;
                if (materials != null)
                    materials[0].SetTexture("_BrushTex", _brushTexture);
            }
            else
            {
                _brushTexture = newBrushTexture;
                CleanBrushTexture();
            }
        }
    }

	private void _SetupPolyIndexTexture() {
		if(polyIndexTexture != null) {
			Color[] _polyIndexColors = polyIndexTexture.GetPixels();
			_polyIndexMap = new byte[_polyIndexColors.Length];
			
			for(int i = 0, cnt = _polyIndexColors.Length; i < cnt; i++) {
				_polyIndexMap[i] = (byte)(_polyIndexColors[i].r * 255.0f);
			}
		}
	}

	private void _SetupMaterials() {
        materials = null;
		SkinnedMeshRenderer smr = GetComponentInChildren<SkinnedMeshRenderer>();

		if(smr != null) {
			// Copy materials
			if(materials == null || materials.Length == 0) {
				materials = smr.materials;
				smr.materials = materials;
			
				materials[0].SetTexture("_BrushTex", brushTexture);
			}
		}
		else {
			MeshRenderer mr = GetComponentInChildren<MeshRenderer>();
			if(mr != null) {
				// Copy materials
				if(materials == null || materials.Length == 0) {
					materials = mr.materials;
					mr.materials = materials;

					materials[0].SetTexture("_BrushTex", brushTexture);
				}
			}
		}
	}

	public void OnDestroy() {
		if(_tcCam != null) {
			_tcCam.UnregisterTemplate(this);
			_tcCam = null;
		}

        if (materials != null) {
            for (int i = 0; i < materials.Length; i++) {
                if (materials[i] != null)
                    Destroy(materials[i]);
            }
            materials = null;
        }

		if(_brushTexture != null) {
			if(_brushTexture.GetType().Equals(typeof(RenderTexture)))
				((RenderTexture)_brushTexture).Release();
			Destroy(_brushTexture);
			_brushTexture = null;
		}

		if(_computeUVsBuffer != null) {
			_computeUVsBuffer.Release();
			_computeUVsBuffer = null;
		}
	}

	public void CleanMainTexture() {
		_SetupMaterials();

		if(materials[0].mainTexture != null) {
			_mainTexture = materials[0].mainTexture;
			materials[0].mainTexture = null;
		}
	}

	public void ShowMainTexture() {
		_SetupMaterials();

		if(materials[0].mainTexture == null) {
			materials[0].mainTexture = _mainTexture;
		}
	}

    // Convert screen space point to TCCamera render texture point.
    public Vector3 ScreenToTCRT(Vector3 position)
    {
        Vector3 point = Vector3.zero;

        // Check if TCCamera instance is available
        if (tcCam != null)
        {
            point = tcCam.ScreenToTCRT(position);
        }

        return point;
    }

    // Convert screen space point to TCCamera render texture normalized point.
    public byte TCRTToPolyIndexIdentifier(Vector3 point)
    {TCRTPixelInfo pixelInfo = tcCam.GetTCRTPixelInfo(point);

        return UVToPolyIndexIdentifier(pixelInfo.uv);
    }

    public byte UVToPolyIndexIdentifier(Vector3 uv)
    {
        byte polyIndexIdentifier = 0;

        if (polyIndexTexture != null)
        {
            Vector3 point = Vector3.zero;

            point.x = uv.x * polyIndexTexture.width;
            point.y = uv.y * polyIndexTexture.height;

            polyIndexIdentifier = GetPolyIndexIdentifier(point);
        }

        return polyIndexIdentifier;
    }

    public void Paint(TouchInfo touchInfo, int brushSize, Color preferredColor, List<Vector2> validUVs = null)
    {
        // Check if template doesn't want painting or method is called before BeginPaint()
        if (!_wantsPaint || !_painting || tcCam == null || identifierForTCCamera == 0) return;

        // Check the brush texture type
        _SetupBrushTexture();

        // Get previous UV point.
        Vector2 currentPos = ScreenToTCRT(touchInfo.position);
        Vector2 prevPos = Vector3.zero;
        if (!_prevPaintPosDict.ContainsKey(touchInfo.id))
        {
            _prevPaintPosDict[touchInfo.id] = currentPos;
        }
        else
        {
            prevPos = _prevPaintPosDict[touchInfo.id];
        }

        // Get poly index identifier of touch point.
        byte polyIndexIdentifier = TCRTToPolyIndexIdentifier(currentPos);

        // If current position and previous position is almost near, ignore painting.
        if ((currentPos - prevPos).sqrMagnitude < 1.0f)
            return;

        if (prevPos == Vector2.zero)
        {
            TCRTPixelInfo info = tcCam.GetTCRTPixelInfo(currentPos);

            if (info.templateId == identifierForTCCamera)
            {
				_uvs.Clear();
				_uvs.Add(info.uv);

				if(supportsComputeShaders) {
					_PaintUV_GPGPU(_uvs, polyIndexIdentifier, brushSize, preferredColor);
				}
				else if (_PerformPaint(info.uv, polyIndexIdentifier, brushSize, preferredColor))
                {
					if (validUVs != null) validUVs.Add(info.uv);
                }
            }
        }
        else
        {
            // get offset
            Vector2 offset = currentPos - prevPos;

            // calculate paint loop count based on pixel offset size
            int paintLoopCount = Mathf.Max(
                Mathf.FloorToInt(Mathf.Abs(offset.x)),
                Mathf.FloorToInt(Mathf.Abs(offset.y)));

            paintLoopCount = Mathf.Min(paintLoopCount, 64);

            // draws only if paint loop count is available
            if (paintLoopCount > 0)
            {
                Vector2 offsetDiv = offset / (float)paintLoopCount;
                Vector2 currentLoopPos = prevPos;

				if(supportsComputeShaders) {
					_uvs.Clear();

					for(int i = 0; i < paintLoopCount + 1; i++) {
						TCRTPixelInfo info = tcCam.GetTCRTPixelInfo(currentLoopPos);
						if (info.templateId == identifierForTCCamera) _uvs.Add(info.uv);
						currentLoopPos += offsetDiv;
					}

					_PaintUV_GPGPU(_uvs, polyIndexIdentifier, brushSize, preferredColor, validUVs);
				}
				else {
					for (int i = 0; i < paintLoopCount + 1; i++)
					{
						TCRTPixelInfo info = tcCam.GetTCRTPixelInfo(currentLoopPos);
						if (info.templateId == identifierForTCCamera)
						{
							if (_PerformPaint(info.uv, polyIndexIdentifier, brushSize, preferredColor))
							{
								if (validUVs != null) validUVs.Add(info.uv);
							}
						}
						
						currentLoopPos += offsetDiv;
					}
				}
				
				_prevPaintPosDict[touchInfo.id] = currentPos;
			}
		}
	}
	
	public void PaintUV(List<Vector2> uvs, byte polyIndexIdentifier, int brushSize, Color preferredColor)
    {
        if (uvs == null || uvs.Count == 0) return;

		if(supportsComputeShaders) {
			_PaintUV_GPGPU(uvs, polyIndexIdentifier, brushSize, preferredColor);
		}
		else {
			for (int i = 0, cnt = uvs.Count; i < cnt; i++)
				_PerformPaint(uvs[i], polyIndexIdentifier, brushSize, preferredColor);
		}
	}
	
	private void _PaintUV_GPGPU(List<Vector2> uvs, byte polyIndexIdentifier, int brushSize, Color preferredColor, List<Vector2> validUVs = null)
	{
		if(uvs == null || uvs.Count == 0) return;

		// Paint range
		Rect range = new Rect(0, 0, 0, 0);
		int brushRadius = brushSize / 2;

		// Check the buffer data size
		int bufferElementCount = _computeUVsBuffer.count;
		while(bufferElementCount < uvs.Count) bufferElementCount = bufferElementCount * 2;

		if(bufferElementCount != _computeUVsBuffer.count) {
			_computeUVsBuffer.Release();
			_computeUVsBuffer = new ComputeBuffer(bufferElementCount, sizeof(float) * 2, ComputeBufferType.Raw);
			_computeUVsBufferArray = new Vector2[bufferElementCount];
		}

		// Calculate the valid number of UV and fill out into array.
		int numberOfUV = 0;
		for(int i = 0; i < uvs.Count; i++) {
			Vector2 uv = uvs[i];
			byte currentPolyIndexIdentifier = UVToPolyIndexIdentifier(uv);
			
			if(currentPolyIndexIdentifier == polyIndexIdentifier) {
				_computeUVsBufferArray[numberOfUV++] = uv;
				if(validUVs != null) validUVs.Add(uv);

				Rect rect = new Rect(uv.x * _brushTextureWidth - brushRadius, uv.y * _brushTextureHeight - brushRadius, brushRadius * 2, brushRadius * 2); 
				if(rect.xMin < 0.0f)
					rect.xMin = 0.0f;
				if(rect.xMax > _brushTextureWidth)
					rect.xMax = _brushTextureWidth;
				if(rect.yMin < 0.0f)
					rect.yMin = 0.0f;
				if(rect.yMax > _brushTextureHeight)
					rect.yMax = _brushTextureHeight;

				if(range.size.sqrMagnitude < 0.001f) {
					range = rect;
				}
				else {
					if(range.xMin > rect.xMin)
						range.xMin = rect.xMin;
					if(range.xMax < rect.xMax)
						range.xMax = rect.xMax;
					if(range.yMin > rect.yMin)
						range.yMin = rect.yMin;
					if(range.yMax < rect.yMax)
						range.yMax = rect.yMax;
				}
			}
		}
		_computeUVsBuffer.SetData(_computeUVsBufferArray);

        RenderTexture prevBrushTexture = RenderTexture.GetTemporary(
            brushTexture.width, 
            brushTexture.height,
            0,
            ((RenderTexture)brushTexture).format, 
            ((RenderTexture)brushTexture).sRGB ? RenderTextureReadWrite.sRGB : RenderTextureReadWrite.Linear);
		Graphics.Blit(brushTexture, prevBrushTexture);

		if(computeShader != null) {
			if(_computePaintKernel == -1) {
				_computePaintKernel = computeShader.FindKernel("TemplateDrawingPaint");
			}

			if(_computePaintKernel != -1) {
				int offsetX = Mathf.RoundToInt(range.x);
				int offsetY = Mathf.RoundToInt(range.y);
				int sizeX = Mathf.RoundToInt(range.width);
				int sizeY = Mathf.RoundToInt(range.height);

				int threadNum = 32;
				int minSize = threadNum;
				while(sizeX > minSize) minSize *= 2;
				sizeX = minSize;

				minSize = threadNum;
				while(sizeY > minSize) minSize *= 2;
				sizeY = minSize;

				computeShader.SetInt("numberOfUV", numberOfUV);
				computeShader.SetTexture(_computePaintKernel, "brushTextureInput", prevBrushTexture);
				computeShader.SetTexture(_computePaintKernel, "brushTextureOutput", brushTexture);
				computeShader.SetInt("brushSize", brushSize);
				computeShader.SetFloats("preferredColor", preferredColor.r, preferredColor.g, preferredColor.b, preferredColor.a);
				computeShader.SetBuffer(_computePaintKernel, "uvs", _computeUVsBuffer);
				computeShader.SetInt("offsetX", offsetX);
				computeShader.SetInt("offsetY", offsetY);

                int numThreads = 16;
				computeShader.Dispatch(_computePaintKernel, sizeX / numThreads, sizeY / numThreads, 1);

			}
			else {
				Debug.LogWarning("Template3D._PaintUV_GPGPU() : Couldn't find the kernel \"TemplateDrawingPaint\"!");
			}
		}

        RenderTexture.ReleaseTemporary(prevBrushTexture);
    }

    private bool _PerformPaint(Vector2 uv, byte polyIndexIdentifier, int brushSize, Color preferredColor)
    {
        byte currentPolyIndexIdentifier = UVToPolyIndexIdentifier(uv);

        bool draw = polyIndexIdentifier == currentPolyIndexIdentifier;

        if (draw)
        {
            if (_innerBrushPaintColors == null || _innerBrushPaintColors.Length != brushSize * brushSize)
            {
                _innerBrushPaintColors = new Color[brushSize * brushSize];
                int centre = brushSize / 2;
                for (int y = 0; y < brushSize; y++)
                {
                    for (int x = 0; x < brushSize; x++)
                    {
                        Color color;
                        float r = (x - centre) * (x - centre) + (y - centre) * (y - centre);
                        float r2 = centre * centre;

                        if (r > r2)
                        {
                            color = new Color(0, 0, 0, 0);
                        }
                        else
                        {
                            color = new Color(1.0f, 1.0f, 1.0f, 1.0f - Mathf.Abs(r / r2));
                        }
                        _innerBrushPaintColors[y * brushSize + x] = color;
                    }
                }
            }
            if (_blendedColors == null || _blendedColors.Length != brushSize * brushSize)
            {
                _blendedColors = new Color[brushSize * brushSize];
            }

            int btx = (int)(uv.x * _brushTextureWidth) - brushSize / 2;
            int bty = (int)(uv.y * _brushTextureHeight) - brushSize / 2;
            int width = brushSize, height = brushSize;

            if (btx < 0)
            {
                width += btx;
                btx = 0;
            }
            else if (btx + width >= _brushTextureWidth)
            {
				if (btx >= _brushTextureWidth)
				{
					btx = _brushTextureWidth - 1;
                    width = 0;
                }
                else
                {
					width = _brushTextureWidth - btx - 1;
				}
            }
            if (bty < 0)
            {
                height += bty;
                bty = 0;
            }
			else if (bty + height >= _brushTextureHeight)
			{
				if (bty >= _brushTextureHeight)
                {
					bty = _brushTextureHeight - 1;
					height = 0;
                }
                else
                {
					height = _brushTextureHeight - bty - 1;
				}
            }

            for (int y = 0, y1 = bty; y < height; y++, y1++)
            {
                for (int x = 0, x1 = btx; x < width; x++, x1++)
                {
					if (x1 >= _brushTextureWidth || y1 >= _brushTextureHeight) continue;
					Color prevColor = _brushTextureBackupColors[y1 * _brushTextureWidth + x1];
                    Color newColor = _innerBrushPaintColors[y * brushSize + x];
                    newColor.r *= preferredColor.r;
                    newColor.g *= preferredColor.g;
                    newColor.b *= preferredColor.b;
                    newColor.a *= preferredColor.a;

                    Color blendedColor = Blend(prevColor, newColor);

                    _blendedColors[y * width + x] = blendedColor;
					_brushTextureBackupColors[y1 * _brushTextureWidth + x1] = blendedColor;
                }
            }

            if (width * height > _blendedColors.Length)
            {
                Debug.Log("Debug Me!");
            }
            if (width * height > 0)
            {
				Texture2D tex = (Texture2D)brushTexture;
				tex.SetPixels(btx, bty, width, height, _blendedColors);
            }
        }

        return draw;
    }

    public void BeginPaint()
    {
        if (_wantsPaint)
        {
            _painting = true;
            CleanMainTexture();
            ShowOutline();
        }
    }

    public void EndPaint(int touchId)
    {
        if (_prevPaintPosDict.ContainsKey(touchId))
        {
            _prevPaintPosDict.Remove(touchId);
        }
        if (_prevPaintPosDict.Count == 0)
        {
            EndPaint();
        }
    }

    public void EndPaint()
    {
        if (_painting)
        {
            FlushPaint();
            _prevPaintPosDict.Clear();
        }
        _painting = false;
    }

    public void FlushPaint()
    {
        if (!supportsComputeShaders)
        {
            Texture2D tex = (Texture2D)brushTexture;
            tex.Apply();
        }
    }

    public void ShowOutline(float outline = 0.008f)
    {
        if (materials != null && materials.Length > 0)
            materials[0].SetFloat("_Outline", outline);
    }

	static public Color Blend (Color baseColor, Color blendColor)
	{
		float outAlpha = baseColor.a * (1.0f - blendColor.a) + blendColor.a;

		if (outAlpha == 0.0f) {
			return Color.clear;
        }
        else
        {
            float outAlphaDiv1 = 1.0f / outAlpha;
			return new Color (
                (baseColor.r * baseColor.a * (1.0f - blendColor.a) + blendColor.r * blendColor.a) * outAlphaDiv1,
                (baseColor.g * baseColor.a * (1.0f - blendColor.a) + blendColor.g * blendColor.a) * outAlphaDiv1,
                (baseColor.b * baseColor.a * (1.0f - blendColor.a) + blendColor.b * blendColor.a) * outAlphaDiv1,
				outAlpha
			);
		}
	}

    public byte GetPolyIndexIdentifier(Vector2 point)
    {
        byte polyIndexIdentifier = 0;

        int pix = Mathf.RoundToInt(point.x);
        int piy = Mathf.RoundToInt(point.y);

        if (polyIndexTexture != null && _polyIndexMap == null)
        {
            _SetupPolyIndexTexture();
        }

        if(_polyIndexMap != null && _polyIndexMap.Length > 0)
            polyIndexIdentifier = _polyIndexMap[Mathf.Min(_polyIndexMap.Length, piy * polyIndexTexture.width + pix)];

        return polyIndexIdentifier;
    }
	

	public void CleanBrushTexture() {
		if(supportsComputeShaders) {
			if(computeShader != null) {
				if(_computeCleanKernel == -1) {
					_computeCleanKernel = computeShader.FindKernel("TemplateDrawingClean");
				}

				if(_computeCleanKernel != -1) {
                    int numThreads = 8;
					computeShader.SetTexture(_computeCleanKernel, "brushTextureOutput", brushTexture);
					computeShader.Dispatch(_computeCleanKernel, _brushTextureWidth / numThreads, _brushTextureHeight / numThreads, 1);
				}
				else {
					Debug.Log("Tempate3D.CleanBrushTexture() : Couldn't find the kernel \"TemplateDrawingClean\"!");
				}
			}
		}
		else {
			Texture2D tex = (Texture2D)brushTexture;
			for(int i = 0, cnt = _brushTextureBackupColors.Length; i < cnt; i++) {
				_brushTextureBackupColors[i] = new Color(1.0f, 1.0f, 1.0f, 0.0f);
			}
			tex.SetPixels(_brushTextureBackupColors);
			tex.Apply();
		}
	}

    public void ResizeBrushTexture(int newWidth, int newHeight)
    {
        if (newWidth < 128) newWidth = 128;
        else if (newWidth > 4096) newWidth = 4096;
        if (newHeight < 128) newHeight = 128;
        else if (newHeight > 4096) newHeight = 4096;

        _brushTextureWidth = newWidth;
        _brushTextureHeight = newHeight;

        _SetupBrushTexture();
    }

	public void LoadBrushTexture(byte[] bytes) {
		if(supportsComputeShaders) {
			Texture2D temporary = new Texture2D(4, 4, TextureFormat.ARGB32, false);
			temporary.LoadImage(bytes);
			temporary.Apply();

			_brushTextureWidth = temporary.width;
			_brushTextureHeight = temporary.height;
			_SetupBrushTexture();

			if(computeShader != null) {
				if(_computeLoadKernel == -1) {
					_computeLoadKernel = computeShader.FindKernel("TemplateDrawingLoad");
				}
				if(_computeLoadKernel != -1) {
                    int numThreads = 8;
					computeShader.SetTexture(_computeLoadKernel, "brushTextureInput", temporary);
					computeShader.SetTexture(_computeLoadKernel, "brushTextureOutput", brushTexture);
					computeShader.Dispatch(_computeLoadKernel, _brushTextureWidth / numThreads, _brushTextureHeight / numThreads, 1);
				}
				else {
					Debug.LogWarning("Template3D.LoadBrushTexture() : Couldn't find the kernel \"TemplateDrawingLoad\"!");
				}
			}
		}
		else {
			Texture2D tex = (Texture2D)brushTexture;
			tex.LoadImage(bytes);
			tex.Apply();
			_brushTextureBackupColors = tex.GetPixels();
		}
	}
}
